### PR TITLE
Add application_name to Postgres stat functions

### PR DESCRIPTION
**Pull request by potocnyj**
We’re collecting application_name for samples in later versions of
Postgres now, update the create-stat-functions scripts to reflect that.

### CODE REVIEW

**Comment by potocnyj** [comment]
@gkristic missed this part of the recent change I did, mind double-checking?

**Comment by gkristic** [comment]
The change looks fine, although I have some concerns on the expressions for 8.4 and 9.0. I created an issue in agents for that.

**Comment by potocnyj** [comment]
Would you prefer that I follow up on the issue first or can I merge this on its own?

**Comment by gkristic** [comment]
Merging this won't hurt, as the concern is about what was already here. And this will certainly fix the case for 9.2 and beyond. So go ahead.

**Pull request merged**
