### PR TITLE
removed spaces and replaced them with hyphens

### PR DESCRIPTION
**Pull request by nachocaru**
ping the OSOM @Andertech

### CODE REVIEW

**Comment by Andertech** [comment]
LGTM @nachocaru :cake:

**Comment by mtrias** [comment]
:ship: please!

**Comment by Andertech** [comment]
@nachocaru we need to run ```grunt publish``` to ship the docs

**Comment by nachocaru** [comment]
On it

**Comment by Andertech** [comment]
It's already done now, go chill and eat :cake:

**Pull request merged**
