### PR TITLE
changing old images

### PR DESCRIPTION
**Pull request by nachocaru**
Will close https://github.com/VividCortex/docs/issues/262

### CODE REVIEW

**Comment by nachocaru** [comment]
@seaparks I couldn't find any image for (https://docs.vividcortex.com/general-reference/metric-anomaly-detection/) could you give me a hand searching for one?

**Comment by seaparks** [comment]
@nachocaru - I can make one. I'll find an example and send you a screenshot.

**Comment by seaparks** [comment]
anomaly

@nachocaru ^

**Comment by nachocaru** [comment]
Great, I'll let you know when it's ready for review, thanks!

**Comment by nachocaru** [comment]
Andrew, I added the final image; could you check it out? https://deploy-preview-270--vividcortex-docs.netlify.com

**Pull request merged**
