### PR TITLE
made the icons appear and also fixed favicon

### PR DESCRIPTION
**Pull request by nachocaru**

### CODE REVIEW

**Comment by mtrias** [comment]
@nachocaru could you explain why this is needed? Perhaps we should spend some time during this sprint fixing the issue so that this kind of changes are not needed anymore?

**Comment by nachocaru** [comment]
Yes I monkey patched this in order to quick fix it and discuss with you the
problem!

**Comment by nachocaru** [comment]
BTW I already reverted this change.

**Comment by mtrias** [comment]
Ok! let me know if/when you want to discuss.

**Pull request merged**
