### PR TITLE
Document new licensing roles

### PR DESCRIPTION
**Pull request by AgentO3**
ref VividCortex/artifacts#322

### CODE REVIEW

**Comment by AgentO3** [comment]
@gkristic

**Comment by gkristic** [comment]
Do we ever say that each of these roles also includes all the permissions for the roles before it? We say "The following is a detailed description of the privileges corresponding to roles", but then don't list all permissions for each one. Anyway... that's not related to this PR.

The addition looks good to me.

**Comment by seaparks** [comment]
@gkristic for whatever reason this was never merged, but it looks like it's still valid. is that true?

**Comment by gkristic** [comment]
Indeed, although there could be some other missing. I don't see `acct:owner:update`, for instance.

**Comment by seaparks** [comment]
@gkristic thanks gus - I created https://github.com/VividCortex/docs/issues/254 and will address.

**Pull request merged**
