### PR TITLE
268 footer widgets

### PR DESCRIPTION
**Pull request by nachocaru**
Will close https://github.com/VividCortex/docs/issues/268

### CODE REVIEW

**Comment by nachocaru** [comment]
PR Summary:
-Replaced the old footer as requested [here](https://github.com/VividCortex/docs/issues/268)
-Replaced the old header as requested [here](https://github.com/VividCortex/docs/issues/268)
-Changed UX for responsive navigation in mobiles
-Changed UX for mobile nav menu button

**Can be checked here:**
https://deploy-preview-271--vividcortex-docs.netlify.com/

**Comment by seaparks** [comment]
@arslotnick @mtrias - Do we have any analytics data on how often people come to our website (www.vividcortex.com, or its children) from the docs site? My only concern with this change is that if you're on the docs site and you're not already a customer, there's now an additional step (clicking the top logo) you need to take to find our more info about VC. The links at the top might not be exact, but they did provide easy access to a lot of content.

**Comment by arslotnick** [comment]
That's a really good point, Andrew, and definitely a case for having a
header menu of some kind. I don't know of any analytics we have that would
show that particular traffic behavior, unfortunately.

Two possible alternatives:
- Match the docs header to the website header, but instead of having the
full drop down menus on docs, just have the main titles and links. So, for
example, have "Product," "Solutions," "Resources," "Company," "Customers,"

[image: Inline image 1]

but none of their children:

[image: Inline image 2]

Also, keep the demo and free trial buttons.


- Eliminate the full header as discussed, but also keep the demo and trial
buttons. That way, we can still drive traffic to our conversion forms from
the docs pages.

I think either of these would be a fine solution for now. Andrew, what do
you think?

**Comment by mtrias** [comment]
Not a single one [in the last year](https://analytics.google.com/analytics/web/#report/trafficsources-referrals/a34462605w62011505p63546907/%3F_u.date00%3D20160109%26_u.date01%3D20170207%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowCount%3D250%26explorer-table.filter%3Ddocs/).
image.

But nevertheless is a good point. I think what Alex suggested makes sense.

**Comment by seaparks** [comment]
Oh wow. The more you know!

Given this data I think we should merge the PR and I can write a new issue to implement the first suggestion, unless it's absolutely trivial to do it now. I'll approve but leave it up to Caru

**Comment by nachocaru** [comment]
I can do whatever you want guys, even in this PR, so please let me know the
final decision and I'll implement it.

**Comment by mtrias** [comment]
I think my vote goes to the last Alex suggestion of having only the main items in the menu plus the call-to-action buttons. It's kind of a good balance.

**Comment by seaparks** [comment]
@mtrias @nachocaru - works for me!

**Comment by arslotnick** [comment]
Sounds good to me too!

**Comment by nachocaru** [comment]
PR Summary:
-Responsive header styling for mobiles
-Improved header UX

Guys a deploy is ready for testing here:
https://deploy-preview-271--vividcortex-docs.netlify.com/

I also added mobile styling so when the browser screen is too narrow or you access it through a phone you are going to see that the header and footer accommodates accordingly.

If everything is okay I'll wait for another "Looks good to me" from @seaparks before merging.

**Comment by mtrias** [comment]
It doesn't look great IMO

image

image

**Comment by nachocaru** [comment]
I don't understand, usually pages don't even show you the responsive face and make you deal with horizontal scrollbars, I really prefer to see the responsive face than that. 
Besides the responsive site was thought to be accessed with a phone so the buttons don't look so big. Maybe we could reduced the media query (?) even though 960px is considered pretty standard.

screenshot_20170210-112818
screenshot_20170210-112847

If what is bothering you is the transition I can work it out so you won't see the menu hiding.

**Comment by nachocaru** [comment]
Another thing we could try instead of an collapsible menu is reduce the font-size, but I always find it more cumbersome to click with my sausage fingers and we have too many links for a single line.

We could use icons also but they will need a legend somewhere since they are specific links and won't be that easy to deduce what they are just by images.

In [another PR](http://deploy-preview-226.vividcortex-docs.netlify.com/) I opted to follow the google material guidelines and simplified a lot the menu leaving just one, but it is not even close to the design we are trying to unify.

Of course I'm open to ideas to try out!!! many heads are always better than one.

**Comment by mtrias** [comment]
Sorry, i was too brief in my last comment. Here's a better explanation:

1. At this screen width, it seems to be lacking margins (actually, this happens in the current site too).
image

2. A weird animation happens when i reduce the screen size (notice the comparison with the current docs site).
image

3. Related to the last point, i'm not sure why reducing the window size, causes the navigation to open. I don't think that's needed.

4. The main navigation looks like stretched horizontally. 100% width looks good on a narrow screen, but not in a wider screen. So in my opinion, this is good:
image

But this is not so good:
image

5. In addition, the way the searching bar is opened 3 lines below, with buttons in between looks odd:
image

6. lastly, may be a personal preference, but having two collapsible navigations is not ideal.
image

**Comment by nachocaru** [comment]
1. Nice, I'll see to fix that issue
2. I think I can work it out
3. The navigation uses a hidden checkbox to open/close, so if you leave it open and enlarge, when you reduce it will appear open; this could be solved EZ.
4. I agree with you, maybe 4, 3 and 2 all three points could be solved by only showing the responsive menu on mobile devices and not in desktops.
5. You are right, I'll fix that.
6. I'm 100% with you in this one; merging both looks terrible weird, we could hide the nav completely. Another solution is to use a floating menu like pendo in the app? (I don't like that they interfere with the reading).

**Comment by nachocaru** [comment]
- Fixed the no margin issue listed above as point 1
- Removed animation triggering when resizing window; basically removed the hide animation of the menu since it's easier and shorter than jQuery
- Added one more step while reducing the screen size. This was done by a middle media query between desktop and phone.
- The menu now has 3 stages: mobile, fully collapsed, phablet only docs navigation collapsed and desktop.
screen shot 2017-02-13 at 5 44 46 pm
screen shot 2017-02-13 at 5 44 52 pm
screen shot 2017-02-13 at 5 45 00 pm
- Search bar is shown for resolutions smaller than 1060px
screen shot 2017-02-13 at 5 45 55 pm
- Fixed bug where the footer was not on the bottom of the page.

I agree with @mtrias in that the two menus thing is not optimal and really think that we could implement either a fixed bottom nav like some mobile apps or a floating menu, but I prefer to defer it to a different PR since this one is too large already.

**Comment by mtrias** [comment]
Here are my comments:

1. Can we try to remove typekit and use the roboto font? I think it makes it harder to spot other design issues (and the opposite, it makes the temporary deploy look ugly and hard to evaluate).
We can do this in a separate branch though, I just wanted to mention so I don't forget.

2. Is the blue bar needed? IMO it is only taking valuable screen space. My vote goes to remove it.
image

3. Odd border (probably needed after we do (2)) so you may ignore this
screen shot 2017-02-14 at 8 19 53 am

4. The logo has a weird effect on hover
image

5. The logo is different to the one in the website (not sure which one is the right one though). They should look equal.
image

6. On the middle jump, the top margin of the logo is not enough. Here's compared with the website which looks better in this regard IMO.
image

7. The colors used in the buttons convey different meanings (this is a pre-existing problem, just more noticeable with bigger buttons)
image

8. The links do not have a hover color, which is more noticeable when you hover in the link area outside of the text. There seems also to be a style for the :active state which exposes different paddings or margins for some menu items
image

9. Missing top margin here
image

10. Finally, this may be just personal taste, but I think the positioning of the elements in the header can be improved a lot. I don't know how to explain it, but just doesn't look great yet.
image

My suggestion would be to, instead of trying to adjust the current html elements with CSS, start a design from scratch that includes those elements in a PSD or similar, and then write the code.

**Comment by nachocaru** [comment]
All right, let's do it, back to the drawing table; I'm gonna revert these last commits until the work done on the footer.

**Comment by nachocaru** [comment]
@mtrias moved the head to the second commit; only footer changes were made.

**Comment by mtrias** [comment]
OK! 2 comments:

1. The footer has the wrong year
image

2. The social network links can't be clicked for some reason

**Comment by nachocaru** [comment]
:finnadie: done.

**Comment by mtrias** [comment]
One last comment, the logo in the footer has the same weird animation on hover
image

**Comment by nachocaru** [comment]
yep, is it too weird? :sweat_smile: :fearful:

**Comment by mtrias** [comment]
It looks like an error to me... is it on purpose ?

**Comment by nachocaru** [comment]
`.vc-logo:hover .c {
   transform: rotateX(180deg);
 } `

**Comment by nachocaru** [comment]
it's just a stupid thing I added, I can easily remove it if you want.

**Comment by mtrias** [comment]
Ok, I didn't know it was on purpose.

Let's :ship: and address this later. I'd suggest improving it and making it consistent throughout all the sites, which will require marketing to review and approve, since the logo is an important matter.

**Pull request merged**
