### PR TITLE
Fix links on content

### PR DESCRIPTION
**Pull request by Andertech**
This fixes the bad links that were left in the markdown of the content pages. ping @mtrias @potocnyj

### CODE REVIEW

**Comment by potocnyj** [comment]
@Andertech I see another one at the bottom of the homepage for the docs - it looks like that's not included here. I'll keep going through and see if I find any others

**Comment by Andertech** [comment]
Thanks @potocnyj I keep missing them :/

**Comment by potocnyj** [comment]
The bottom of the troubleshooting page has another too

**Comment by potocnyj** [comment]
I think we've got them all now, and if we missed any we can always do a follow-up on this. Thanks for fixing them! :beer:

**Pull request merged**
