### PR TITLE
165 scroll fixed navigation

### PR DESCRIPTION
**Pull request by nachocaru**
Closes https://github.com/VividCortex/docs/issues/165

### CODE REVIEW

**Comment by nachocaru** [comment]
@mtrias should I add the scroll to top button also?

**Comment by mtrias** [comment]
Not necessary IMO

**Comment by seaparks** [comment]
@nachocaru hey there! did this get released? the sidebar of nav items isn't scrolling for me in the most recent version of Chrome.

**Comment by nachocaru** [comment]
Nope, I'm preparing something different here:
http://deploy-preview-226.vividcortex-docs.netlify.com/

Would you like to give it a test?

**Comment by seaparks** [comment]
Woahhh, super cool! If it's still pending on Tuesday I would love to play around and test!

**Pull request closed without merging**
